# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('index', models.CharField(default='index', max_length=255, primary_key=True, serialize=False, verbose_name='Индекс')),
                ('department', models.CharField(max_length=255, verbose_name='Кафедра')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('part', models.CharField(choices=[('Базовая часть', 'Базовая часть'), ('Вариативная часть', 'Вариативная часть')], max_length=255, verbose_name='Базовая/вариативная часть')),
                ('kindofdis', models.CharField(choices=[('Обязательная дисциплина', 'Обязательная дисциплина'), ('Дисциплина по выбору', 'Дисциплина по выбору'), ('Факультатив', 'Факультатив')], max_length=255, verbose_name='Обязательная дисциплина/дисциплина по выбору/факультатив')),
                ('weeks', models.IntegerField(default=0, verbose_name='Количество недель')),
                ('lectures', models.IntegerField(default=0, verbose_name='Часов лекций')),
                ('labs', models.IntegerField(default=0, verbose_name='Часов лабораторных')),
                ('pracs', models.IntegerField(default=0, verbose_name='Часов практики')),
                ('srs', models.IntegerField(default=0, verbose_name='Часов СРС')),
                ('krprkt', models.IntegerField(default=0, verbose_name='КР/ПРКТ')),
                ('izkr', models.IntegerField(default=0, verbose_name='ИЗ/КР')),
                ('ctrl', models.CharField(max_length=255, verbose_name='Контроль')),
                ('group_name', models.CharField(max_length=255, verbose_name='Дисциплина для группы')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(default='GroupName', max_length=255, verbose_name='Имя группы')),
                ('form', models.CharField(max_length=255, verbose_name='Форма обучения')),
                ('direction', models.CharField(max_length=255, verbose_name='Код направления подготовки')),
                ('dirname', models.CharField(max_length=255, verbose_name='Направление подготовки')),
                ('profile', models.CharField(max_length=255, verbose_name='Профиль подготовки')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('dep', models.CharField(max_length=255, verbose_name='Кафедра')),
                ('protocolnum', models.TextField(max_length=255, verbose_name='Номер протокола')),
                ('date', models.CharField(max_length=255, verbose_name='Дата протокола')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test3.Discipline', verbose_name='Дисциплина')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test3.Group', verbose_name='Группа')),
            ],
        ),
    ]
