# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='degree',
            field=models.CharField(default=0, max_length=255, verbose_name='Ученая степень'),
            preserve_default=False,
        ),
    ]
