# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0004_auto_20170516_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='addlit',
        ),
        migrations.RemoveField(
            model_name='group',
            name='aim',
        ),
        migrations.RemoveField(
            model_name='group',
            name='attestation',
        ),
        migrations.RemoveField(
            model_name='group',
            name='fond',
        ),
        migrations.RemoveField(
            model_name='group',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='group',
            name='intensity',
        ),
        migrations.RemoveField(
            model_name='group',
            name='internet',
        ),
        migrations.RemoveField(
            model_name='group',
            name='lectures',
        ),
        migrations.RemoveField(
            model_name='group',
            name='listLit',
        ),
        migrations.RemoveField(
            model_name='group',
            name='listit',
        ),
        migrations.RemoveField(
            model_name='group',
            name='mainlit',
        ),
        migrations.RemoveField(
            model_name='group',
            name='method',
        ),
        migrations.RemoveField(
            model_name='group',
            name='methodTable',
        ),
        migrations.RemoveField(
            model_name='group',
            name='planResults',
        ),
        migrations.RemoveField(
            model_name='group',
            name='pracs',
        ),
        migrations.RemoveField(
            model_name='group',
            name='prepex',
        ),
        migrations.RemoveField(
            model_name='group',
            name='preplec',
        ),
        migrations.RemoveField(
            model_name='group',
            name='preprac',
        ),
        migrations.RemoveField(
            model_name='group',
            name='tableBase',
        ),
        migrations.AddField(
            model_name='program',
            name='addlit',
            field=models.TextField(default=0, verbose_name='Перечень основной и дополнительной литературы. Дополнительная литература'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='aim',
            field=models.TextField(default=0, verbose_name='Цель дисциплины'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='attestation',
            field=models.TextField(default=0, verbose_name='Форма промежуточной аттестации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='fond',
            field=models.TextField(default=0, verbose_name='Фонд оценочных средств для проведения промежуточной аттестации обучающих-ся по дисциплине '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='goal',
            field=models.TextField(default=0, verbose_name='Задачи дисциплины'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='intensity',
            field=models.TextField(default=0, verbose_name='Общая трудоемкость дисциплины'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='internet',
            field=models.TextField(default=0, verbose_name='Перечень ресурсов информационно-телекоммуникационной сети «Интернет»'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='lectures',
            field=models.TextField(default=0, verbose_name='Темы лекций, их содержание, трудоемкость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='listLit',
            field=models.TextField(default=0, verbose_name='Перечень учебно-методического обеспечения для самостоятельной работы обу-чающихся по дисциплине'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='listit',
            field=models.TextField(default=0, verbose_name='Перечень информационных технологий, используемых при осуществлении образовательного процесса по дисциплине, включая перечень программного обеспе-чения и информационных справочных систем'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='mainlit',
            field=models.TextField(default=0, verbose_name='Перечень основной и дополнительной литературы. Основная литература'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='method',
            field=models.TextField(default=0, verbose_name='Методические указания для обучающихся по освоению дисциплины'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='methodTable',
            field=models.TextField(default=0, verbose_name='Методическое обеспечение самостоятельной работы обучающихся'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='planResults',
            field=models.TextField(default=0, verbose_name='Перечень планируемых результатов обучения по дисциплине, соотнесенных с планиру-емыми результатами освоения образовательной программы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='pracs',
            field=models.TextField(default=0, verbose_name='Состав и объем практических занятий'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='prepex',
            field=models.TextField(default=0, verbose_name='Подготовка к экзамену'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='preplec',
            field=models.TextField(default=0, verbose_name='Подготовка к лекции'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='preprac',
            field=models.TextField(default=0, verbose_name='Подготовка к практическим занятиям'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='tableBase',
            field=models.TextField(default=0, verbose_name='Описание материально-технической базы, необходимой для осуществления образовательного процесса по дисциплине'),
            preserve_default=False,
        ),
    ]
