# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0005_auto_20170516_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='id',
        ),
        migrations.AlterField(
            model_name='program',
            name='protocolnum',
            field=models.TextField(max_length=255, primary_key=True, serialize=False, verbose_name='Номер протокола'),
        ),
    ]
