# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0007_auto_20170516_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='disciplineContent',
            field=models.TextField(default=0, verbose_name='Перечень планируемых результатов обучения по дисциплине, соотнесенных с планируемыми результатами освоения образовательной программы'),
            preserve_default=False,
        ),
    ]
