# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0008_program_disciplinecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='disciplineContent',
            field=models.TextField(verbose_name='Содержание дисциплины, структурированное по разделам, с указанием отведенного на них количества академических часов и видов учебных занятий'),
        ),
    ]
