# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0010_auto_20170523_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='attestation',
            field=models.CharField(max_length=255, verbose_name='Форма промежуточной аттестации'),
        ),
    ]
