# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0011_auto_20170523_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='intensity',
            field=models.CharField(help_text='Сколько зачетных единиц?', max_length=10, verbose_name='Общая трудоемкость дисциплины'),
        ),
    ]
