# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0012_auto_20170523_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='labs',
            field=models.TextField(default=0, verbose_name='Состав и объем лаборатоных занятий'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='intensity',
            field=models.CharField(max_length=10, verbose_name='Общая трудоемкость дисциплины'),
        ),
    ]
