# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0013_auto_20170524_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='fond',
            field=models.TextField(verbose_name='Фонд оценочных средств для проведения промежуточной аттестации обучающихся по дисциплине '),
        ),
        migrations.AlterField(
            model_name='program',
            name='labs',
            field=models.TextField(verbose_name='Состав и объем лаборартоных занятий'),
        ),
        migrations.AlterField(
            model_name='program',
            name='listLit',
            field=models.TextField(verbose_name='Перечень учебно-методического обеспечения для самостоятельной работы обучающихся по дисциплине'),
        ),
        migrations.AlterField(
            model_name='program',
            name='listit',
            field=models.TextField(verbose_name='Перечень информационных технологий, используемых при осуществлении образовательного процесса по дисциплине, включая перечень программного обеспечения и информационных справочных систем'),
        ),
    ]
