# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0014_auto_20170524_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='competention',
            field=models.CharField(default=0, max_length=255, verbose_name='Код компетенции'),
            preserve_default=False,
        ),
    ]
