# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0015_discipline_competention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minobrnayki', models.CharField(max_length=255, verbose_name='Шапка титульного листа')),
                ('decan', models.CharField(max_length=255, verbose_name='Декан факультета')),
                ('approve', models.CharField(max_length=255, verbose_name='Кто утверждает')),
                ('approvePosition', models.CharField(max_length=255, verbose_name='Должность утверждающего')),
            ],
        ),
    ]
