# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0016_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test3.Document', verbose_name='Оформление документа'),
        ),
    ]
