# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0017_program_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='Template', max_length=255, verbose_name='Название шаблона'),
            preserve_default=False,
        ),
    ]
