# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0018_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='fed',
            field=models.CharField(default='федеральное государственное бюджетное образовательное учреждение высшего образования', max_length=255, verbose_name='федеральное государственное бюджетное образовательное учреждение высшего образования'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='minobrnayki',
            field=models.CharField(max_length=255, verbose_name='МИНОБРНАУКИ РОССИИ'),
        ),
    ]
